[package]
name = "x86_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x86 = { path = "../../sleigh3rust/x86" }
x86_lib = { path = "../x86_lib" }
