[package]
name = "arm8_be_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arm8_be = { path = "../../sleigh3rust/arm8_be" }
arm_lib = { path = "../arm_lib" }
