[package]
name = "z80_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sleigh4rust = { "path" = "../../sleigh4rust"}
csv = "1"
serde = { version = "1.0.154", features = ["derive"] }
