[package]
name = "arm4_le_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arm4_le = { path = "../../sleigh3rust/arm4_le" }
arm_lib = { path = "../arm_lib" }
