[package]
name = "superh4_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sleigh4rust = { "path" = "../../sleigh4rust"}
serde = { version = "1", features = ["derive"] }
csv = "1"
