[package]
name = "z180_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z180 = { path = "../../sleigh3rust/z180" }
z80_lib = { path = "../z80_lib" }
