[package]
name = "v850_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v850 = { path = "../../sleigh3rust/v850" }
csv = "1"
serde = { version = "1.0.154", features = ["derive"] }
